import type { Tender } from "@/types/tender";

// Mock dataset — swap with real API responses by editing src/lib/api.ts
export const mockTenders: Tender[] = [
  {
    id: "T-2024-0142",
    title: "Reconstruction of Highway M-03 Section",
    organization: "Ministry of Infrastructure",
    budget: 4_800_000,
    finalPrice: 6_720_000,
    participantsCount: 1,
    riskScore: 92,
    riskLevel: "HIGH",
    winner: "Alpha Construction LLC",
    category: "Construction",
    publishedAt: "2024-09-12",
    deadline: "2025-06-30",
    description:
      "Full reconstruction of a 12 km section including drainage, asphalt resurfacing, and roadside infrastructure.",
    riskFlags: [
      { severity: "critical", message: "Single bidder detected" },
      { severity: "critical", message: "Final price 40% above market average" },
      { severity: "warning", message: "Winner has 80% win rate with this organization" },
    ],
  },
  {
    id: "T-2024-0138",
    title: "Supply of Medical Equipment for Regional Hospitals",
    organization: "Ministry of Health",
    budget: 1_200_000,
    finalPrice: 1_185_000,
    participantsCount: 6,
    riskScore: 18,
    riskLevel: "LOW",
    winner: "MedSupply Group",
    category: "Healthcare",
    publishedAt: "2024-08-30",
    deadline: "2025-05-15",
    description: "Procurement of diagnostic imaging devices and consumables for 8 regional hospitals.",
    riskFlags: [{ severity: "warning", message: "All checks passed within normal thresholds" }],
  },
  {
    id: "T-2024-0151",
    title: "IT Infrastructure Modernization",
    organization: "Department of Digital Services",
    budget: 850_000,
    finalPrice: 1_020_000,
    participantsCount: 2,
    riskScore: 64,
    riskLevel: "MEDIUM",
    winner: "NetCore Solutions",
    category: "IT Services",
    publishedAt: "2024-09-05",
    deadline: "2025-07-01",
    description: "Network hardware refresh, server consolidation, and cybersecurity tooling rollout.",
    riskFlags: [
      { severity: "warning", message: "Only 2 bidders participated" },
      { severity: "warning", message: "Final price 20% above budget" },
    ],
  },
  {
    id: "T-2024-0119",
    title: "School Cafeteria Catering Services",
    organization: "Department of Education",
    budget: 420_000,
    finalPrice: 415_000,
    participantsCount: 8,
    riskScore: 12,
    riskLevel: "LOW",
    winner: "FreshMeals Co.",
    category: "Catering",
    publishedAt: "2024-07-22",
    deadline: "2025-08-31",
    description: "Annual catering contract for 24 schools with daily lunch service for ~6,000 students.",
    riskFlags: [{ severity: "warning", message: "Healthy competition observed" }],
  },
  {
    id: "T-2024-0160",
    title: "Office Building Renovation — Government Quarter",
    organization: "Ministry of Infrastructure",
    budget: 2_300_000,
    finalPrice: 3_220_000,
    participantsCount: 1,
    riskScore: 88,
    riskLevel: "HIGH",
    winner: "Alpha Construction LLC",
    category: "Construction",
    publishedAt: "2024-09-18",
    deadline: "2025-09-30",
    description: "Interior renovation, HVAC modernization, and accessibility upgrades for two office buildings.",
    riskFlags: [
      { severity: "critical", message: "Single bidder detected" },
      { severity: "critical", message: "Final price 40% above budget" },
      { severity: "warning", message: "Same winner as 4 other recent tenders" },
    ],
  },
  {
    id: "T-2024-0147",
    title: "Public Transport Fleet Maintenance",
    organization: "City Transit Authority",
    budget: 980_000,
    finalPrice: 990_000,
    participantsCount: 5,
    riskScore: 22,
    riskLevel: "LOW",
    winner: "AutoService Plus",
    category: "Transportation",
    publishedAt: "2024-08-14",
    deadline: "2026-08-14",
    description: "Two-year contract for routine maintenance of 240 buses across the metro fleet.",
    riskFlags: [{ severity: "warning", message: "Competitive pricing observed" }],
  },
  {
    id: "T-2024-0155",
    title: "Pharmaceutical Procurement — Q4",
    organization: "Ministry of Health",
    budget: 3_400_000,
    finalPrice: 4_080_000,
    participantsCount: 2,
    riskScore: 71,
    riskLevel: "HIGH",
    winner: "PharmaDist International",
    category: "Healthcare",
    publishedAt: "2024-09-22",
    deadline: "2025-12-31",
    description: "Bulk procurement of essential medicines for state pharmacies for Q4 distribution.",
    riskFlags: [
      { severity: "critical", message: "Final price 20% above budget" },
      { severity: "warning", message: "Winner has 65% win rate with this organization" },
      { severity: "warning", message: "Only 2 bidders" },
    ],
  },
  {
    id: "T-2024-0162",
    title: "Municipal Park Landscaping",
    organization: "City Council",
    budget: 180_000,
    finalPrice: 175_500,
    participantsCount: 7,
    riskScore: 9,
    riskLevel: "LOW",
    winner: "GreenSpace Designs",
    category: "Landscaping",
    publishedAt: "2024-09-25",
    deadline: "2025-04-30",
    description: "Redesign and replanting of three central municipal parks with native species.",
    riskFlags: [{ severity: "warning", message: "Strong competition, fair pricing" }],
  },
  {
    id: "T-2024-0166",
    title: "Cybersecurity Audit Services",
    organization: "Department of Digital Services",
    budget: 320_000,
    finalPrice: 380_000,
    participantsCount: 3,
    riskScore: 48,
    riskLevel: "MEDIUM",
    winner: "SecureLogic Audit",
    category: "IT Services",
    publishedAt: "2024-09-30",
    deadline: "2025-05-30",
    description: "Comprehensive penetration testing and security posture assessment for 12 government systems.",
    riskFlags: [
      { severity: "warning", message: "Final price 19% above budget" },
      { severity: "warning", message: "Limited bidder pool for specialized service" },
    ],
  },
  {
    id: "T-2024-0170",
    title: "Bridge Repair — Northern District",
    organization: "Ministry of Infrastructure",
    budget: 1_500_000,
    finalPrice: 2_100_000,
    participantsCount: 1,
    riskScore: 85,
    riskLevel: "HIGH",
    winner: "Alpha Construction LLC",
    category: "Construction",
    publishedAt: "2024-10-02",
    deadline: "2025-10-15",
    description: "Structural repair and load-bearing reinforcement of two bridges on the northern ring road.",
    riskFlags: [
      { severity: "critical", message: "Single bidder detected" },
      { severity: "critical", message: "Final price 40% above market" },
      { severity: "warning", message: "Same contractor pattern across infrastructure tenders" },
    ],
  },
  {
    id: "T-2024-0173",
    title: "Library Digital Archive System",
    organization: "Department of Education",
    budget: 240_000,
    finalPrice: 235_000,
    participantsCount: 4,
    riskScore: 28,
    riskLevel: "LOW",
    winner: "ArchiveTech Inc.",
    category: "IT Services",
    publishedAt: "2024-10-05",
    deadline: "2025-06-15",
    description: "Implementation of a digital archive and search system for the national library network.",
    riskFlags: [{ severity: "warning", message: "All key indicators within normal range" }],
  },
  {
    id: "T-2024-0180",
    title: "Ambulance Vehicle Procurement",
    organization: "Ministry of Health",
    budget: 1_100_000,
    finalPrice: 1_320_000,
    participantsCount: 2,
    riskScore: 58,
    riskLevel: "MEDIUM",
    winner: "MedTransport Vehicles",
    category: "Healthcare",
    publishedAt: "2024-10-10",
    deadline: "2025-07-20",
    description: "Procurement of 22 fully equipped ambulances with cardiac monitoring equipment.",
    riskFlags: [
      { severity: "warning", message: "Final price 20% above budget" },
      { severity: "warning", message: "Only 2 bidders" },
    ],
  },
];

export const mockApplications: import("@/types/tender").Application[] = [
  {
    id: "A-001",
    tenderId: "T-2024-0142",
    companyId: "c-acme",
    companyName: "Acme Corp",
    proposedPrice: 4_950_000,
    productName: "Highway resurfacing package",
    productDescription: "Full-stack road reconstruction crew with drainage and signage.",
    status: "Lost",
    submittedAt: "2024-09-15",
  },
  {
    id: "A-002",
    tenderId: "T-2024-0138",
    companyId: "c-acme",
    companyName: "Acme Corp",
    proposedPrice: 1_180_000,
    productName: "Diagnostic imaging suite",
    productDescription: "MRI + CT bundle with 3-year service contract.",
    status: "Won",
    submittedAt: "2024-09-01",
  },
  {
    id: "A-003",
    tenderId: "T-2024-0151",
    companyId: "c-nova",
    companyName: "Nova Solutions",
    proposedPrice: 920_000,
    productName: "Network modernization stack",
    productDescription: "Switches, firewalls, SIEM rollout across 14 sites.",
    status: "Pending",
    submittedAt: "2024-09-08",
  },
];
